services:
  web:
    build: .
    ports:
      - "5900:5900"

    volumes:
      - ./vault:/vault
      - ./output:/output
      - ./data.json:/config.json

  server:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./output:/usr/share/nginx/html
    depends_on:
      - web

    dns: 8.8.8.8
